---
sudo: false
dist: xenial
language: ruby
if: tag IS blank
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.5
      bundler_args: --without system_tests
      env: PUPPET_VERSION="~> 5.0"
      script:
        - 'bundle show puppet'
        - 'bundle exec rake metadata_lint syntax spec'
    - rvm: 2.5.3
      bundler_args: --without system_tests
      env: PUPPET_VERSION="~> 6.0"
      script:
        - 'bundle show puppet'
        - 'bundle exec rake metadata_lint syntax spec'
    - rvm: 2.4.5
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_hypervisor=docker BEAKER_set=docker/centos-6
      script: bundle exec rake beaker
      services: docker
    - rvm: 2.5.3
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_hypervisor=docker BEAKER_set=docker/centos-6
      script: bundle exec rake beaker
      services: docker
    - rvm: 2.4.5
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_hypervisor=docker BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
    - rvm: 2.5.3
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_hypervisor=docker BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
    - rvm: 2.4.5
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_hypervisor=docker BEAKER_set=docker/debian-8
      script: bundle exec rake beaker
      services: docker
    - rvm: 2.5.3
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_hypervisor=docker BEAKER_set=docker/debian-8
      script: bundle exec rake beaker
      services: docker
    - rvm: 2.4.5
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_hypervisor=docker BEAKER_set=docker/ubuntu-1604
      script: bundle exec rake beaker
      services: docker
    - rvm: 2.5.3
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_hypervisor=docker BEAKER_set=docker/ubuntu-1604
      script: bundle exec rake beaker
      services: docker
    - rvm: 2.4.5
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_hypervisor=docker BEAKER_set=docker/ubuntu-1804
      script: bundle exec rake beaker
      services: docker
    - rvm: 2.5.3
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_hypervisor=docker BEAKER_set=docker/ubuntu-1804
      script: bundle exec rake beaker
      services: docker
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
