---
sudo: false
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle show puppet'
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
    - bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu1804-64 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    - bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu1604-64 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    - bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu1404-64 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    - bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos8-64 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    - bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos7-64 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos6-64 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian10-64 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian9-64 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian8-64 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
